# Generated by Django 4.2.23 on 2025-07-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
